version: '3.8'

services:
  simple-proxy:
    image: simple-proxy

    container_name: simple-proxy
    # host:container
    ports:
      - "3001:3001"

    environment:
      PORT: 3001
      HOST: 0.0.0.0
      TARGET_URL: https://openrouter.ai
      PROXY_PATH: /openrouter-api

    restart: unless-stopped
