version: '3.8'

services:
  simple-proxy:
    build: .
    image: simple_proxy

    container_name: simple_proxy
    # host:container
    ports:
      - "3002:3002"

    environment:
      PORT: 3002
      HOST: "0.0.0.0"
      OPENROUTER_URL: "https://openrouter.ai"
      # should start with /
      OPENROUTER_PATH: "/openrouter-api"

    restart: unless-stopped
